version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "3001:3001"
    user: "1001:1001"
    volumes:
      - ./server/data.json:/app/server/data.json
      - ./server/user.json:/app/server/user.json
      - ./server/invite_codes.json:/app/server/invite_codes.json
